version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - nilerr
    - revive
    - staticcheck
    - unused
    - sqlclosecheck
    - rowserrcheck
    - noctx
    - contextcheck
    - errorlint
    - nilnil
    - nilnesserr
    - exhaustive
    - nolintlint
    - loggercheck
    - sloglint
    - misspell
    - makezero
    - unconvert
    - wastedassign
    - modernize
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofumpt
    - goimports
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/adnope/quiver)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
